# Generated by Django 5.2.3 on 2025-07-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseappointment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawyers.lawyerprofile'),
        ),
    ]
