# Generated by Django 5.2.3 on 2025-07-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseappointment',
            name='location',
        ),
        migrations.AddField(
            model_name='caseappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
