# Generated by Django 5.2.4 on 2025-07-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_caseappointment_location_and_more'),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.generaluserprofile'),
        ),
    ]
