# Generated by Django 5.2.4 on 2025-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_caseappointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
