# Generated by Django 5.2.4 on 2025-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_caseappointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
