# Generated by Django 5.2.3 on 2025-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='specialization',
            field=models.CharField(choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('corporate', 'Corporate Law'), ('family', 'Family Law'), ('intellectual_property', 'Intellectual Property Law'), ('general', 'General Practice')], default='general', max_length=255),
        ),
    ]
