# Generated by Django 5.2.3 on 2025-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_alter_lawyerprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='experience_years',
            field=models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('11-15', '11-15 years'), ('16+', '16+ years')], max_length=100),
        ),
    ]
