# Generated by Django 5.2.3 on 2025-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_alter_lawyerprofile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='cases_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='clients_served',
            field=models.IntegerField(default=0),
        ),
    ]
