# Generated by Django 5.2.4 on 2025-07-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_casedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.BooleanField(default=False)),
                ('photo_id', models.FileField(blank=True, null=True, upload_to='photo_id/')),
                ('cop', models.FileField(blank=True, null=True, upload_to='cop/')),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lawyers.lawyerprofile')),
            ],
        ),
    ]
