# Generated by Django 5.2.4 on 2025-07-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('lawyers', '0008_lawyerdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='lawyers.lawyerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='clients.generaluserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lawyer')},
            },
        ),
    ]
