# Generated by Django 5.2.4 on 2025-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_alter_transaction_options_remove_transaction_hire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
